version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  groups:
    types:
      patterns:
        - "@types/*"
    linting:
      patterns:
        - "@tree-company/eslint-config"
        - "@typescript-eslint/*"
        - "eslint"
        - "prettier"
        - "typescript-eslint"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - robbevp
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - robbevp
